metadata_dir = "/tmp/meta"
data_dir = "/tmp/data"
db_engine = "sqlite"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "0.0.0.0:3901"
rpc_secret = "aa5ff4f3b19a5405f73c281d6f31c6efb565ab8a97b136f4c1bb6da6ed440675"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.localhost"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.garage.localhost"
index = "index.html"

[k2v_api]
api_bind_addr = "[::]:3904"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "5J56IBcZuakACBoZD8zSXBngNmpS3rXAzdv8tTGKEuA="
metrics_token = "BZVY83NqZ9CGqAfEbrqKKxGbqNFWuIfA6RyM56tLQrE="
