name: Release Registry on DockerHub

on:
  push:
    paths-ignore:
      - ".github/**"
      - "README.md"
      - "Dockerfile"
      - "Makefile"
      - "version.txt"
      - "docs/**"
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Setup Dependencies
        run: cd src && go mod tidy

      - name: Run Tests
        run: cd src && go test -v

  build:
    runs-on: ubuntu-latest
    needs: [test]
    services:
      docker:
        image: docker:dind
        options: --privileged
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Dependencies
        run: |
          apt update && apt install -y curl make
          curl -fsSL https://get.docker.com -o get-docker.sh && bash get-docker.sh

      - name: Build Registry
        run: make release version=$(cat version.txt)

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_REGISTRY_LOGIN}}
          password: ${{secrets.DOCKER_REGISRTY_PWD}}

      - name: Push to Docker Hub
        run: make push version=$(cat version.txt)
